import type { QuizQuestion } from '../types';

export const sampleQuestions: QuizQuestion[] = [
  {
    id: '1',
    category_id: 'wc2026-teams',
    question_en: 'Which country is hosting the 2026 FIFA World Cup?',
    question_ar: 'أي دولة تستضيف كأس العالم 2026؟',
    answers_en: ['USA, Canada, Mexico', 'Qatar', 'Russia', 'Germany'],
    answers_ar: ['الولايات المتحدة، كندا، المكسيك', 'قطر', 'روسيا', 'ألمانيا'],
    correct_answer_index: 0,
    explanation_en: 'The 2026 World Cup is jointly hosted by USA, Canada, and Mexico.',
    explanation_ar: 'كأس العالم 2026 تستضيفه الولايات المتحدة وكندا والمكسيك.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '2',
    category_id: 'wc-history',
    question_en: 'Which country has won the most FIFA World Cup titles?',
    question_ar: 'أي دولة فازت بأكبر عدد من ألقاب كأس العالم؟',
    answers_en: ['Germany', 'Argentina', 'Brazil', 'Italy'],
    answers_ar: ['ألمانيا', 'الأرجنتين', 'البرازيل', 'إيطاليا'],
    correct_answer_index: 2,
    explanation_en: 'Brazil has won 5 World Cup titles (1958, 1962, 1970, 1994, 2002).',
    explanation_ar: 'البرازيل فازت بـ 5 ألقاب في كأس العالم.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '3',
    category_id: 'guess-flag',
    question_en: 'Which country has a green, white, and red flag with an eagle in the center?',
    question_ar: 'أي دولة علمها أخضر وأبيض وأحمر مع نسر في الوسط؟',
    answers_en: ['Egypt', 'Mexico', 'Italy', 'Syria'],
    answers_ar: ['مصر', 'المكسيك', 'إيطاليا', 'سوريا'],
    correct_answer_index: 1,
    explanation_en: 'Mexico\'s flag features green, white, and red stripes with an eagle eating a snake.',
    explanation_ar: 'علم المكسيك يضم خطوطاً خضراء وبيضاء وحمراء ونسراً يأكل أفعى.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '4',
    category_id: 'guess-player',
    question_en: 'Which player is known as "The King of Football" and led Brazil to 3 World Cup wins?',
    question_ar: 'أي لاعب يُعرف بـ "ملك كرة القدم" وقاد البرازيل لـ 3 ألقاب في كأس العالم؟',
    answers_en: ['Ronaldo', 'Pelé', 'Ronaldinho', 'Neymar'],
    answers_ar: ['رونالدو', 'بيليه', 'رونالدينيو', 'نيمار'],
    correct_answer_index: 1,
    explanation_en: 'Pelé won the World Cup in 1958, 1962, and 1970.',
    explanation_ar: 'بيليه فاز بكأس العالم أعوام 1958 و1962 و1970.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '5',
    category_id: 'stadiums',
    question_en: 'Which stadium is known as the "Home of Football" in England?',
    question_ar: 'أي ملعب يُعرف بـ "بيت كرة القدم" في إنجلترا؟',
    answers_en: ['Old Trafford', 'Anfield', 'Wembley Stadium', 'Emirates Stadium'],
    answers_ar: ['أولد ترافورد', 'آنفيلد', 'ملعب ويمبلي', 'ملعب الإمارات'],
    correct_answer_index: 2,
    explanation_en: 'Wembley Stadium is the national stadium of England.',
    explanation_ar: 'ملعب ويمبلي هو الملعب الوطني لإنجلترا.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '6',
    category_id: 'arab-teams',
    question_en: 'Which Arab country reached the World Cup semi-finals in 2022?',
    question_ar: 'أي دولة عربية وصلت إلى نصف نهائي كأس العالم 2022؟',
    answers_en: ['Saudi Arabia', 'Morocco', 'Egypt', 'Tunisia'],
    answers_ar: ['السعودية', 'المغرب', 'مصر', 'تونس'],
    correct_answer_index: 1,
    explanation_en: 'Morocco made history by reaching the semi-finals of the 2022 World Cup.',
    explanation_ar: 'المغرب صنع التاريخ بوصوله إلى نصف نهائي كأس العالم 2022.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '7',
    category_id: 'wc2026-teams',
    question_en: 'Which team is in Group C of the 2026 World Cup alongside Brazil?',
    question_ar: 'أي منتخب في المجموعة C في كأس العالم 2026 إلى جانب البرازيل؟',
    answers_en: ['Morocco', 'Spain', 'Germany', 'England'],
    answers_ar: ['المغرب', 'إسبانيا', 'ألمانيا', 'إنجلترا'],
    correct_answer_index: 0,
    explanation_en: 'Group C: Brazil, Morocco, Haiti, Scotland.',
    explanation_ar: 'المجموعة C: البرازيل، المغرب، هايتي، اسكتلندا.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '8',
    category_id: 'wc-history',
    question_en: 'In which year was the first FIFA World Cup held?',
    question_ar: 'في أي سنة أُقيم أول كأس عالم؟',
    answers_en: ['1926', '1930', '1934', '1950'],
    answers_ar: ['1926', '1930', '1934', '1950'],
    correct_answer_index: 1,
    explanation_en: 'The first World Cup was held in Uruguay in 1930.',
    explanation_ar: 'أقيم أول كأس عالم في الأوروغواي عام 1930.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '9',
    category_id: 'guess-player',
    question_en: 'Who holds the record for most goals in World Cup history?',
    question_ar: 'من يحمل الرقم القياسي لأكبر عدد من الأهداف في تاريخ كأس العالم؟',
    answers_en: ['Ronaldo (Brazil)', 'Miroslav Klose', 'Marta', 'Just Fontaine'],
    answers_ar: ['رونالدو (البرازيل)', 'ميروسلاف كلوزه', 'مارتا', 'جوست فونتين'],
    correct_answer_index: 1,
    explanation_en: 'Miroslav Klose scored 16 goals across 4 World Cups.',
    explanation_ar: 'ميروسلاف كلوزه سجل 16 هدفاً في 4 نسخ من كأس العالم.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '10',
    category_id: 'stadiums',
    question_en: 'The Maracanã Stadium is located in which city?',
    question_ar: 'ملعب الماراكانا يقع في أي مدينة؟',
    answers_en: ['São Paulo', 'Rio de Janeiro', 'Buenos Aires', 'Lisbon'],
    answers_ar: ['ساو باولو', 'ريو دي جانيرو', 'بوينس آيرس', 'لشبونة'],
    correct_answer_index: 1,
    explanation_en: 'Maracanã is in Rio de Janeiro, Brazil.',
    explanation_ar: 'الماراكانا يقع في ريو دي جانيرو، البرازيل.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '11',
    category_id: 'european-teams',
    question_en: 'Which European country has never missed a World Cup tournament?',
    question_ar: 'أي دولة أوروبية لم تتغيب عن أي بطولة كأس عالم؟',
    answers_en: ['England', 'Germany', 'Italy', 'Spain'],
    answers_ar: ['إنجلترا', 'ألمانيا', 'إيطاليا', 'إسبانيا'],
    correct_answer_index: 1,
    explanation_en: 'Germany has participated in every World Cup since 1930.',
    explanation_ar: 'ألمانيا شاركت في كل نسخ كأس العالم منذ 1930.',
    difficulty: 'hard',
    active: true,
  },
  {
    id: '12',
    category_id: 'asian-teams',
    question_en: 'Which Asian country finished 4th in the 2002 World Cup?',
    question_ar: 'أي دولة آسيوية حلت في المركز الرابع في كأس العالم 2002؟',
    answers_en: ['Japan', 'South Korea', 'Saudi Arabia', 'Iran'],
    answers_ar: ['اليابان', 'كوريا الجنوبية', 'السعودية', 'إيران'],
    correct_answer_index: 1,
    explanation_en: 'South Korea finished 4th in the 2002 World Cup they co-hosted.',
    explanation_ar: 'كوريا الجنوبية حلت رابعاً في كأس العالم 2002 الذي استضافته.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '13',
    category_id: 'lebanese-fan-culture',
    question_en: 'Which Lebanese football club is based in Beirut and wears yellow?',
    question_ar: 'أي نادي كرة قدم لبناني مقره بيروت ويرتدي الأصفر؟',
    answers_en: ['Al-Ansar', 'Nejmeh SC', 'Al-Ahed', 'Racing Beirut'],
    answers_ar: ['الأنصار', 'النجمة', 'العهد', 'الراسينغ'],
    correct_answer_index: 1,
    explanation_en: 'Nejmeh SC, based in Beirut, wears yellow and is one of Lebanon\'s most popular clubs.',
    explanation_ar: 'نادي النجمة الرياضي مقره بيروت ويرتدي الأصفر.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '14',
    category_id: 'african-teams',
    question_en: 'Which African team was the first to reach the World Cup quarter-finals?',
    question_ar: 'أي منتخب أفريقي كان أول من وصل إلى ربع نهائي كأس العالم؟',
    answers_en: ['Nigeria', 'Senegal', 'Cameroon', 'Ghana'],
    answers_ar: ['نيجيريا', 'السنغال', 'الكاميرون', 'غانا'],
    correct_answer_index: 2,
    explanation_en: 'Cameroon reached the quarter-finals in 1990.',
    explanation_ar: 'الكاميرون وصلت إلى ربع النهائي في 1990.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '15',
    category_id: 'finals-history',
    question_en: 'Which two teams played the 2022 World Cup final?',
    question_ar: 'أي فريقين لعبا نهائي كأس العالم 2022؟',
    answers_en: ['France vs Croatia', 'Argentina vs France', 'Brazil vs Germany', 'Spain vs Netherlands'],
    answers_ar: ['فرنسا ضد كرواتيا', 'الأرجنتين ضد فرنسا', 'البرازيل ضد ألمانيا', 'إسبانيا ضد هولندا'],
    correct_answer_index: 1,
    explanation_en: 'Argentina defeated France on penalties in the 2022 final.',
    explanation_ar: 'الأرجنتين هزمت فرنسا بركلات الترجيح في نهائي 2022.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '16',
    category_id: 'football-rules',
    question_en: 'How many substitutions are allowed in a World Cup match?',
    question_ar: 'كم عدد التبديلات المسموح بها في مباراة كأس العالم؟',
    answers_en: ['3', '4', '5', '6'],
    answers_ar: ['3', '4', '5', '6'],
    correct_answer_index: 2,
    explanation_en: 'Teams can make up to 5 substitutions in a World Cup match.',
    explanation_ar: 'يمكن للفرق إجراء ما يصل إلى 5 تبديلات في مباراة كأس العالم.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '17',
    category_id: 'famous-goals',
    question_en: 'Who scored the "Hand of God" goal in 1986?',
    question_ar: 'من سجل هدف "يد الله" في 1986؟',
    answers_en: ['Maradona', 'Messi', 'Pelé', 'Zidane'],
    answers_ar: ['مارادونا', 'ميسي', 'بيليه', 'زيدان'],
    correct_answer_index: 0,
    explanation_en: 'Diego Maradona scored the famous Hand of God goal against England in 1986.',
    explanation_ar: 'دييغو مارادونا سجل هدف يد الله الشهير ضد إنجلترا في 1986.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '18',
    category_id: 'penalty-drama',
    question_en: 'Which team won the 1994 World Cup on penalties?',
    question_ar: 'أي فريق فاز بكأس العالم 1994 بركلات الترجيح؟',
    answers_en: ['Italy', 'Brazil', 'Germany', 'Argentina'],
    answers_ar: ['إيطاليا', 'البرازيل', 'ألمانيا', 'الأرجنتين'],
    correct_answer_index: 1,
    explanation_en: 'Brazil beat Italy on penalties in the 1994 final.',
    explanation_ar: 'البرازيل هزمت إيطاليا بركلات الترجيح في نهائي 1994.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '19',
    category_id: 'captains-legends',
    question_en: 'Who captained Argentina to victory in the 2022 World Cup?',
    question_ar: 'من قاد الأرجنتين للفوز بكأس العالم 2022؟',
    answers_en: ['Angel Di Maria', 'Lionel Messi', 'Emiliano Martinez', 'Julian Alvarez'],
    answers_ar: ['أنخيل دي ماريا', 'ليونيل ميسي', 'إيميليانو مارتينيز', 'خوليان ألفاريز'],
    correct_answer_index: 1,
    explanation_en: 'Lionel Messi captained Argentina to their 2022 World Cup triumph.',
    explanation_ar: 'ليونيل ميسي قاد الأرجنتين للفوز بكأس العالم 2022.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '20',
    category_id: 'wc2026-teams',
    question_en: 'Which team is in Group J alongside Argentina?',
    question_ar: 'أي منتخب في المجموعة J إلى جانب الأرجنتين؟',
    answers_en: ['Brazil, Portugal, France', 'Algeria, Austria, Jordan', 'England, Croatia, Ghana', 'Spain, Germany, Italy'],
    answers_ar: ['البرازيل، البرتغال، فرنسا', 'الجزائر، النمسا، الأردن', 'إنجلترا، كرواتيا، غانا', 'إسبانيا، ألمانيا، إيطاليا'],
    correct_answer_index: 1,
    explanation_en: 'Group J: Argentina, Algeria, Austria, Jordan.',
    explanation_ar: 'المجموعة J: الأرجنتين، الجزائر، النمسا، الأردن.',
    difficulty: 'hard',
    active: true,
  },
  {
    id: '21',
    category_id: 'south-american-teams',
    question_en: 'How many World Cups has Argentina won?',
    question_ar: 'كم عدد كؤوس العالم التي فازت بها الأرجنتين؟',
    answers_en: ['2', '3', '4', '1'],
    answers_ar: ['2', '3', '4', '1'],
    correct_answer_index: 1,
    explanation_en: 'Argentina has won 3 World Cups: 1978, 1986, and 2022.',
    explanation_ar: 'الأرجنتين فازت بـ 3 كؤوس عالم: 1978 و1986 و2022.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '22',
    category_id: 'lebanese-fan-culture',
    question_en: 'What is the most popular sport in Lebanon?',
    question_ar: 'ما هي الرياضة الأكثر شعبية في لبنان؟',
    answers_en: ['Basketball', 'Football', 'Tennis', 'Swimming'],
    answers_ar: ['كرة السلة', 'كرة القدم', 'التنس', 'السباحة'],
    correct_answer_index: 1,
    explanation_en: 'Football is the most popular sport in Lebanon.',
    explanation_ar: 'كرة القدم هي الرياضة الأكثر شعبية في لبنان.',
    difficulty: 'easy',
    active: true,
  },
  {
    id: '23',
    category_id: 'wc2026-teams',
    question_en: 'Which African teams are participating in the 2026 World Cup?',
    question_ar: 'ما هي المنتخبات الأفريقية المشاركة في كأس العالم 2026؟',
    answers_en: ['South Africa, Morocco, Tunisia, Egypt, Senegal, Côte d\'Ivoire, Algeria, Ghana', 'Nigeria, Cameroon, Ghana, Egypt', 'Morocco, Senegal, Algeria, Tunisia', 'South Africa, Egypt, Morocco, Algeria'],
    answers_ar: ['جنوب أفريقيا، المغرب، تونس، مصر، السنغال، ساحل العاج، الجزائر، غانا', 'نيجيريا، الكاميرون، غانا، مصر', 'المغرب، السنغال، الجزائر، تونس', 'جنوب أفريقيا، مصر، المغرب، الجزائر'],
    correct_answer_index: 0,
    explanation_en: '8 African teams qualified: South Africa, Morocco, Tunisia, Egypt, Senegal, Côte d\'Ivoire, Algeria, Ghana.',
    explanation_ar: '8 منتخبات أفريقية تأهلت: جنوب أفريقيا، المغرب، تونس، مصر، السنغال، ساحل العاج، الجزائر، غانا.',
    difficulty: 'hard',
    active: true,
  },
  {
    id: '24',
    category_id: 'wc2026-teams',
    question_en: 'Which team is in Group L?',
    question_ar: 'أي منتخب في المجموعة L؟',
    answers_en: ['England, Croatia, Ghana, Panama', 'France, Senegal, Iraq, Norway', 'Portugal, Colombia, Uzbekistan, Congo DR', 'Spain, Cabo Verde, Saudi Arabia, Uruguay'],
    answers_ar: ['إنجلترا، كرواتيا، غانا، بنما', 'فرنسا، السنغال، العراق، النرويج', 'البرتغال، كولومبيا، أوزبكستان، الكونغو الديمقراطية', 'إسبانيا، كابو فيردي، السعودية، الأوروغواي'],
    correct_answer_index: 0,
    explanation_en: 'Group L: England, Croatia, Ghana, Panama.',
    explanation_ar: 'المجموعة L: إنجلترا، كرواتيا، غانا، بنما.',
    difficulty: 'medium',
    active: true,
  },
  {
    id: '25',
    category_id: 'wc-history',
    question_en: 'Who won the Golden Ball in the 2014 World Cup?',
    question_ar: 'من فاز بالكرة الذهبية في كأس العالم 2014؟',
    answers_en: ['Thomas Müller', 'Lionel Messi', 'James Rodríguez', 'Manuel Neuer'],
    answers_ar: ['توماس مولر', 'ليونيل ميسي', 'جيمس رودريغيز', 'مانويل نوير'],
    correct_answer_index: 1,
    explanation_en: 'Lionel Messi won the Golden Ball in 2014.',
    explanation_ar: 'ليونيل ميسي فاز بالكرة الذهبية في 2014.',
    difficulty: 'medium',
    active: true,
  },
];
