INSERT INTO quiz_questions (category_id, question_en, question_ar, answers_en, answers_ar, correct_answer_index, difficulty, explanation_en, explanation_ar, active) VALUES
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "Which team plays in North America?",
  "أي منتخب يلعب في أمريكا الشمالية؟",
  "[\"Mexico\",\"USA\",\"Sweden\",\"IR Iran\"]",
  "[\"المكسيك\",\"الولايات المتحدة\",\"السويد\",\"إيران\"]",
  0,
  'easy',
  "Mexico location",
  "موقع المكسيك",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "Which team plays in Africa?",
  "أي منتخب يلعب في أفريقيا؟",
  "[\"Spain\",\"Türkiye\",\"South Africa\",\"Mexico\"]",
  "[\"إسبانيا\",\"تركيا\",\"جنوب أفريقيا\",\"المكسيك\"]",
  2,
  'easy',
  "South Africa location",
  "موقع جنوب أفريقيا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "Which team plays in Europe?",
  "أي منتخب يلعب في أوروبا؟",
  "[\"Scotland\",\"Ghana\",\"USA\",\"Korea Republic\"]",
  "[\"اسكتلندا\",\"غانا\",\"الولايات المتحدة\",\"كوريا الجنوبية\"]",
  3,
  'easy',
  "Korea Republic location",
  "موقع كوريا الجنوبية",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "Which team plays in South America?",
  "أي منتخب يلعب في أمريكا الجنوبية؟",
  "[\"Australia\",\"Czechia\",\"Egypt\",\"Colombia\"]",
  "[\"أستراليا\",\"التشيك\",\"مصر\",\"كولومبيا\"]",
  1,
  'easy',
  "Czechia location",
  "موقع التشيك",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "Which team plays in Asia?",
  "أي منتخب يلعب في آسيا؟",
  "[\"Canada\",\"Ecuador\",\"Sweden\",\"Scotland\"]",
  "[\"كندا\",\"الإكوادور\",\"السويد\",\"اسكتلندا\"]",
  0,
  'easy',
  "Canada location",
  "موقع كندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Lionel Messi?",
  "ما جنسية ليونيل ميسي؟",
  "[\"Lewandowski\",\"Lionel Messi\",\"Osimhen\",\"De Bruyne\"]",
  "[\"ليفاندوفسكي\",\"ليونيل ميسي\",\"أوسيمين\",\"دي بروين\"]",
  1,
  'easy',
  "Lionel Messi is Argentina",
  "ليونيل ميسي من الأرجنتين",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Cristiano Ronaldo?",
  "ما جنسية كريستيانو رونالدو؟",
  "[\"Mbappé\",\"Cristiano Ronaldo\",\"Lewandowski\",\"Son Heung-min\"]",
  "[\"مبابي\",\"كريستيانو رونالدو\",\"ليفاندوفسكي\",\"سون هيونغ مين\"]",
  1,
  'easy',
  "Cristiano Ronaldo is Portugal",
  "كريستيانو رونالدو من البرتغال",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Neymar?",
  "ما جنسية نيمار؟",
  "[\"Neymar\",\"Osimhen\",\"Son Heung-min\",\"Lewandowski\"]",
  "[\"نيمار\",\"أوسيمين\",\"سون هيونغ مين\",\"ليفاندوفسكي\"]",
  0,
  'easy',
  "Neymar is Brazil",
  "نيمار من البرازيل",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Mbappé?",
  "ما جنسية مبابي؟",
  "[\"Mbappé\",\"Osimhen\",\"Lewandowski\",\"Lionel Messi\"]",
  "[\"مبابي\",\"أوسيمين\",\"ليفاندوفسكي\",\"ليونيل ميسي\"]",
  0,
  'easy',
  "Mbappé is France",
  "مبابي من فرنسا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Salah?",
  "ما جنسية صلاح؟",
  "[\"Salah\",\"Mahrez\",\"Lionel Messi\",\"Kane\"]",
  "[\"صلاح\",\"مح رز\",\"ليونيل ميسي\",\"كين\"]",
  0,
  'easy',
  "Salah is Egypt",
  "صلاح من مصر",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Haaland?",
  "ما جنسية هالاند؟",
  "[\"Musiala\",\"Haaland\",\"Mahrez\",\"Mané\"]",
  "[\"موسيالا\",\"هالاند\",\"مح رز\",\"ماني\"]",
  1,
  'easy',
  "Haaland is Norway",
  "هالاند من النرويج",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Lewandowski?",
  "ما جنسية ليفاندوفسكي؟",
  "[\"De Bruyne\",\"Mbappé\",\"Lewandowski\",\"Modrić\"]",
  "[\"دي بروين\",\"مبابي\",\"ليفاندوفسكي\",\"مودريتش\"]",
  2,
  'easy',
  "Lewandowski is Poland",
  "ليفاندوفسكي من بولندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is De Bruyne?",
  "ما جنسية دي بروين؟",
  "[\"Mané\",\"Bellingham\",\"De Bruyne\",\"Vinícius Jr\"]",
  "[\"ماني\",\"بيلينغهام\",\"دي بروين\",\"فينيسيوس\"]",
  2,
  'easy',
  "De Bruyne is Belgium",
  "دي بروين من بلجيكا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Modrić?",
  "ما جنسية مودريتش؟",
  "[\"Modrić\",\"Benzema\",\"Haaland\",\"Vinícius Jr\"]",
  "[\"مودريتش\",\"بنزيما\",\"هالاند\",\"فينيسيوس\"]",
  0,
  'easy',
  "Modrić is Croatia",
  "مودريتش من كرواتيا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Benzema?",
  "ما جنسية بنزيما؟",
  "[\"Kane\",\"De Bruyne\",\"Benzema\",\"Lionel Messi\"]",
  "[\"كين\",\"دي بروين\",\"بنزيما\",\"ليونيل ميسي\"]",
  2,
  'easy',
  "Benzema is France",
  "بنزيما من فرنسا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Mané?",
  "ما جنسية ماني؟",
  "[\"Mané\",\"Lionel Messi\",\"Mahrez\",\"Vinícius Jr\"]",
  "[\"ماني\",\"ليونيل ميسي\",\"مح رز\",\"فينيسيوس\"]",
  0,
  'easy',
  "Mané is Senegal",
  "ماني من السنغال",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Mahrez?",
  "ما جنسية مح رز؟",
  "[\"Neymar\",\"Mbappé\",\"Mané\",\"Mahrez\"]",
  "[\"نيمار\",\"مبابي\",\"ماني\",\"مح رز\"]",
  3,
  'easy',
  "Mahrez is Algeria",
  "مح رز من الجزائر",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Osimhen?",
  "ما جنسية أوسيمين؟",
  "[\"Griezmann\",\"Vinícius Jr\",\"Salah\",\"Osimhen\"]",
  "[\"غريزمان\",\"فينيسيوس\",\"صلاح\",\"أوسيمين\"]",
  3,
  'easy',
  "Osimhen is Nigeria",
  "أوسيمين من نيجيريا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Son Heung-min?",
  "ما جنسية سون هيونغ مين؟",
  "[\"Neymar\",\"Son Heung-min\",\"De Bruyne\",\"Salah\"]",
  "[\"نيمار\",\"سون هيونغ مين\",\"دي بروين\",\"صلاح\"]",
  1,
  'easy',
  "Son Heung-min is South Korea",
  "سون هيونغ مين من كوريا الجنوبية",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Kane?",
  "ما جنسية كين؟",
  "[\"Kane\",\"Mbappé\",\"Mané\",\"Bellingham\"]",
  "[\"كين\",\"مبابي\",\"ماني\",\"بيلينغهام\"]",
  0,
  'easy',
  "Kane is England",
  "كين من إنجلترا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Griezmann?",
  "ما جنسية غريزمان؟",
  "[\"Griezmann\",\"De Bruyne\",\"Mbappé\",\"Mbappé\"]",
  "[\"غريزمان\",\"دي بروين\",\"مبابي\",\"مبابي\"]",
  0,
  'easy',
  "Griezmann is France",
  "غريزمان من فرنسا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Vinícius Jr?",
  "ما جنسية فينيسيوس؟",
  "[\"Vinícius Jr\",\"Osimhen\",\"Neymar\",\"Griezmann\"]",
  "[\"فينيسيوس\",\"أوسيمين\",\"نيمار\",\"غريزمان\"]",
  0,
  'easy',
  "Vinícius Jr is Brazil",
  "فينيسيوس من البرازيل",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Bellingham?",
  "ما جنسية بيلينغهام؟",
  "[\"Bellingham\",\"Osimhen\",\"Son Heung-min\",\"Lewandowski\"]",
  "[\"بيلينغهام\",\"أوسيمين\",\"سون هيونغ مين\",\"ليفاندوفسكي\"]",
  0,
  'easy',
  "Bellingham is England",
  "بيلينغهام من إنجلترا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "What nationality is Musiala?",
  "ما جنسية موسيالا؟",
  "[\"Musiala\",\"Bellingham\",\"Griezmann\",\"Benzema\"]",
  "[\"موسيالا\",\"بيلينغهام\",\"غريزمان\",\"بنزيما\"]",
  0,
  'easy',
  "Musiala is Germany",
  "موسيالا من ألمانيا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'finals-history'),
  "Which World Cup final was held at the Maracanã?",
  "أي نهائي كأس عالم أُقيم في الماراكانا؟",
  "[\"1950 (Uruguay vs Brazil)\",\"2014 (Germany vs Argentina)\",\"1998 (France vs Brazil)\",\"1970 (Brazil vs Italy)\"]",
  "[\"1950 (الأوروغواي ضد البرازيل)\",\"2014 (ألمانيا ضد الأرجنتين)\",\"1998 (فرنسا ضد البرازيل)\",\"1970 (البرازيل ضد إيطاليا)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'finals-history'),
  "Which was the only all-European World Cup final?",
  "ما هو النهائي الأوروبي الوحيد في كأس العالم؟",
  "[\"Spain vs Netherlands (2010)\",\"Italy vs France (2006)\",\"France vs Croatia (2018)\",\"Germany vs Argentina (2014)\"]",
  "[\"إسبانيا ضد هولندا (2010)\",\"إيطاليا ضد فرنسا (2006)\",\"فرنسا ضد كرواتيا (2018)\",\"ألمانيا ضد الأرجنتين (2014)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'finals-history'),
  "Which country hosted the 2010 World Cup?",
  "أي دولة استضافت كأس العالم 2010؟",
  "[\"South Africa\",\"Brazil\",\"Germany\",\"Russia\"]",
  "[\"جنوب أفريقيا\",\"البرازيل\",\"ألمانيا\",\"روسيا\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'finals-history'),
  "Which country hosted the 2014 World Cup?",
  "أي دولة استضافت كأس العالم 2014؟",
  "[\"Brazil\",\"Qatar\",\"Russia\",\"South Africa\"]",
  "[\"البرازيل\",\"قطر\",\"روسيا\",\"جنوب أفريقيا\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'finals-history'),
  "Which country hosted the 2018 World Cup?",
  "أي دولة استضافت كأس العالم 2018؟",
  "[\"Russia\",\"Qatar\",\"Brazil\",\"South Africa\"]",
  "[\"روسيا\",\"قطر\",\"البرازيل\",\"جنوب أفريقيا\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'penalty-drama'),
  "How many penalty shootouts happened in the 2022 WC?",
  "كم عدد ركلات الترجيح في كأس العالم 2022؟",
  "[\"4 shootouts\",\"2\",\"3\",\"5\"]",
  "[\"4\",\"2\",\"3\",\"5\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'penalty-drama'),
  "Which team won the 2006 WC on penalties?",
  "أي فريق فاز بكأس العالم 2006 بركلات الترجيح؟",
  "[\"Italy\",\"France\",\"Germany\",\"Portugal\"]",
  "[\"إيطاليا\",\"فرنسا\",\"ألمانيا\",\"البرتغال\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'penalty-drama'),
  "Who missed the crucial penalty in the 1994 WC final?",
  "من أضاع ركلة الجزاء الحاسمة في نهائي 1994؟",
  "[\"Roberto Baggio\",\"Franco Baresi\",\"Daniele Massaro\",\"Alberico Evani\"]",
  "[\"روبرتو باجيو\",\"فرانكو باريزي\",\"دانييلي ماسارو\",\"البيريكو إيفاني\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'captains-legends'),
  "Which captain lifted the 2022 World Cup trophy?",
  "أي كابتن رفع كأس العالم 2022؟",
  "[\"Lionel Messi\",\"Hugo Lloris\",\"Harry Kane\",\"Cristiano Ronaldo\"]",
  "[\"ليونيل ميسي\",\"هوغو لوريس\",\"هاري كين\",\"كريستيانو رونالدو\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'captains-legends'),
  "Which captain lifted the 2018 World Cup trophy?",
  "أي كابتن رفع كأس العالم 2018؟",
  "[\"Hugo Lloris\",\"Lionel Messi\",\"Kylian Mbappé\",\"Antoine Griezmann\"]",
  "[\"هوغو لوريس\",\"ليونيل ميسي\",\"كيليان مبابي\",\"أنطوان غريزمان\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'captains-legends'),
  "How many captains have won the World Cup as captain?",
  "كم عدد القادة الذين فازوا بكأس العالم كقائد؟",
  "[\"17 captains (1930-2022)\",\"22 captains\",\"10 captains\",\"All winning captains\"]",
  "[\"17 قائداً (1930-2022)\",\"22 قائداً\",\"10 قادة\",\"جميع القادة الفائزين\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'famous-goals'),
  "Who scored the goal that won the 2010 World Cup for Spain?",
  "من سجل الهدف الذي فاز بكأس العالم 2010 لإسبانيا؟",
  "[\"Andrés Iniesta\",\"David Villa\",\"Xavi\",\"Fernando Torres\"]",
  "[\"أندريس إنييستا\",\"دافيد فيا\",\"تشافي\",\"فرناندو توريس\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'famous-goals'),
  "Who scored the header goal in the 1998 WC final?",
  "من سجل الهدف الرأسي في نهائي 1998؟",
  "[\"Zinedine Zidane\",\"Emmanuel Petit\",\"Lilian Thuram\",\"Youri Djorkaeff\"]",
  "[\"زين الدين زيدان\",\"إيمانويل بوتي\",\"ليليان تورام\",\"يوري دجوركاييف\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'famous-goals'),
  "Who scored the only goal of the 2010 WC final?",
  "من سجل الهدف الوحيد في نهائي 2010؟",
  "[\"Andrés Iniesta\",\"David Villa\",\"Xavi\",\"Sergio Ramos\"]",
  "[\"أندريس إنييستا\",\"دافيد فيا\",\"تشافي\",\"سيرخيو راموس\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "Which country has won the Copa América the most?",
  "أي دولة فازت بكوبا أمريكا لأكبر عدد؟",
  "[\"Argentina (16)\",\"Uruguay (15)\",\"Brazil (9)\",\"Chile (2)\"]",
  "[\"الأرجنتين (16)\",\"الأوروغواي (15)\",\"البرازيل (9)\",\"تشيلي (2)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "Which South American country has no World Cup title?",
  "أي دولة من أمريكا الجنوبية ليس لديها لقب كأس عالم؟",
  "[\"Chile, Colombia, Paraguay, Ecuador, Peru\",\"Argentina\",\"Uruguay\",\"Brazil\"]",
  "[\"تشيلي، كولومبيا، باراغواي، الإكوادور، بيرو\",\"الأرجنتين\",\"الأوروغواي\",\"البرازيل\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "Who is Argentina's second all-time top scorer?",
  "من هو ثاني هداف الأرجنتين التاريخي؟",
  "[\"Gabriel Batistuta (56 goals)\",\"Sergio Agüero (42 goals)\",\"Diego Maradona (34 goals)\",\"Ángel Di María (31 goals)\"]",
  "[\"غابرييل باتيستوتا (56 هدفاً)\",\"سيرخيو أغويرو (42 هدفاً)\",\"دييغو مارادونا (34 هدفاً)\",\"أنخيل دي ماريا (31 هدفاً)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is the minimum referee count for a FIFA match?",
  "ما هو الحد الأدنى لعدد الحكام في مباراة الفيفا؟",
  "[\"4 (1 referee + 2 assistants + 4th official)\",\"3\",\"5\",\"2\"]",
  "[\"4 (حكم + 2 مساعدين + حكم رابع)\",\"3\",\"5\",\"2\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "Can a substitute be sent off before entering the pitch?",
  "هل يمكن طرد بديل قبل دخوله الملعب؟",
  "[\"Yes\",\"No\",\"Only for violent conduct\",\"Only if they argue\"]",
  "[\"نعم\",\"لا\",\"فقط للسلوك العنيف\",\"فقط إذا احتج\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "Does a goal count if the referee blows the whistle before it enters?",
  "هل تحتسب هدف إذا أطلق الحكم الصافرة قبل دخوله؟",
  "[\"No\",\"Yes\",\"Depends on the referee\",\"Only if it was offside\"]",
  "[\"لا\",\"نعم\",\"يعتمد على الحكم\",\"فقط إذا كان تسللاً\"]",
  0,
  'hard',
  "",
  "",
  true);
