INSERT INTO quiz_questions (category_id, question_en, question_ar, answers_en, answers_ar, correct_answer_index, difficulty, explanation_en, explanation_ar, active) VALUES
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Mexico?",
  "ما هو رمز الفيفا لـ المكسيك？",
  "[\"Mexico\",\"Haiti\",\"Netherlands\",\"Saudi Arabia\"]",
  "[\"المكسيك\",\"هايتي\",\"هولندا\",\"السعودية\"]",
  0,
  'hard',
  "Mexico code varies",
  "رمز المكسيك متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for South Africa?",
  "ما هو رمز الفيفا لـ جنوب أفريقيا？",
  "[\"South Africa\",\"Scotland\",\"Japan\",\"Uruguay\"]",
  "[\"جنوب أفريقيا\",\"اسكتلندا\",\"اليابان\",\"الأوروغواي\"]",
  0,
  'hard',
  "South Africa code varies",
  "رمز جنوب أفريقيا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Korea Republic?",
  "ما هو رمز الفيفا لـ كوريا الجنوبية？",
  "[\"Korea Republic\",\"USA\",\"Tunisia\",\"France\"]",
  "[\"كوريا الجنوبية\",\"الولايات المتحدة\",\"تونس\",\"فرنسا\"]",
  0,
  'hard',
  "Korea Republic code varies",
  "رمز كوريا الجنوبية متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Czechia?",
  "ما هو رمز الفيفا لـ التشيك？",
  "[\"Czechia\",\"Paraguay\",\"Sweden\",\"Senegal\"]",
  "[\"التشيك\",\"باراغواي\",\"السويد\",\"السنغال\"]",
  0,
  'hard',
  "Czechia code varies",
  "رمز التشيك متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Canada?",
  "ما هو رمز الفيفا لـ كندا？",
  "[\"Canada\",\"Australia\",\"Belgium\",\"Iraq\"]",
  "[\"كندا\",\"أستراليا\",\"بلجيكا\",\"العراق\"]",
  0,
  'hard',
  "Canada code varies",
  "رمز كندا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Bosnia and Herzegovina?",
  "ما هو رمز الفيفا لـ البوسنة والهرسك？",
  "[\"Bosnia and Herzegovina\",\"Türkiye\",\"Egypt\",\"Norway\"]",
  "[\"البوسنة والهرسك\",\"تركيا\",\"مصر\",\"النرويج\"]",
  0,
  'hard',
  "Bosnia and Herzegovina code varies",
  "رمز البوسنة والهرسك متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Qatar?",
  "ما هو رمز الفيفا لـ قطر？",
  "[\"Qatar\",\"Germany\",\"IR Iran\",\"Argentina\"]",
  "[\"قطر\",\"ألمانيا\",\"إيران\",\"الأرجنتين\"]",
  0,
  'hard',
  "Qatar code varies",
  "رمز قطر متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Switzerland?",
  "ما هو رمز الفيفا لـ سويسرا？",
  "[\"Switzerland\",\"Curaçao\",\"New Zealand\",\"Algeria\"]",
  "[\"سويسرا\",\"كوراساو\",\"نيوزيلندا\",\"الجزائر\"]",
  0,
  'hard',
  "Switzerland code varies",
  "رمز سويسرا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Brazil?",
  "ما هو رمز الفيفا لـ البرازيل？",
  "[\"Brazil\",\"Côte d'Ivoire\",\"Spain\",\"Austria\"]",
  "[\"البرازيل\",\"ساحل العاج\",\"إسبانيا\",\"النمسا\"]",
  0,
  'hard',
  "Brazil code varies",
  "رمز البرازيل متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Morocco?",
  "ما هو رمز الفيفا لـ المغرب？",
  "[\"Morocco\",\"Ecuador\",\"Cabo Verde\",\"Jordan\"]",
  "[\"المغرب\",\"الإكوادور\",\"كابو فيردي\",\"الأردن\"]",
  0,
  'hard',
  "Morocco code varies",
  "رمز المغرب متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Haiti?",
  "ما هو رمز الفيفا لـ هايتي？",
  "[\"Haiti\",\"Netherlands\",\"Saudi Arabia\",\"Portugal\"]",
  "[\"هايتي\",\"هولندا\",\"السعودية\",\"البرتغال\"]",
  0,
  'hard',
  "Haiti code varies",
  "رمز هايتي متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Scotland?",
  "ما هو رمز الفيفا لـ اسكتلندا？",
  "[\"Scotland\",\"Japan\",\"Uruguay\",\"Colombia\"]",
  "[\"اسكتلندا\",\"اليابان\",\"الأوروغواي\",\"كولومبيا\"]",
  0,
  'hard',
  "Scotland code varies",
  "رمز اسكتلندا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for USA?",
  "ما هو رمز الفيفا لـ الولايات المتحدة？",
  "[\"USA\",\"Tunisia\",\"France\",\"Uzbekistan\"]",
  "[\"الولايات المتحدة\",\"تونس\",\"فرنسا\",\"أوزبكستان\"]",
  0,
  'hard',
  "USA code varies",
  "رمز الولايات المتحدة متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Paraguay?",
  "ما هو رمز الفيفا لـ باراغواي？",
  "[\"Paraguay\",\"Sweden\",\"Senegal\",\"Congo DR\"]",
  "[\"باراغواي\",\"السويد\",\"السنغال\",\"الكونغو الديمقراطية\"]",
  0,
  'hard',
  "Paraguay code varies",
  "رمز باراغواي متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Australia?",
  "ما هو رمز الفيفا لـ أستراليا？",
  "[\"Australia\",\"Belgium\",\"Iraq\",\"England\"]",
  "[\"أستراليا\",\"بلجيكا\",\"العراق\",\"إنجلترا\"]",
  0,
  'hard',
  "Australia code varies",
  "رمز أستراليا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Türkiye?",
  "ما هو رمز الفيفا لـ تركيا？",
  "[\"Türkiye\",\"Egypt\",\"Norway\",\"Croatia\"]",
  "[\"تركيا\",\"مصر\",\"النرويج\",\"كرواتيا\"]",
  0,
  'hard',
  "Türkiye code varies",
  "رمز تركيا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Germany?",
  "ما هو رمز الفيفا لـ ألمانيا？",
  "[\"Germany\",\"IR Iran\",\"Argentina\",\"Ghana\"]",
  "[\"ألمانيا\",\"إيران\",\"الأرجنتين\",\"غانا\"]",
  0,
  'hard',
  "Germany code varies",
  "رمز ألمانيا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Curaçao?",
  "ما هو رمز الفيفا لـ كوراساو？",
  "[\"Curaçao\",\"New Zealand\",\"Algeria\",\"Panama\"]",
  "[\"كوراساو\",\"نيوزيلندا\",\"الجزائر\",\"بنما\"]",
  0,
  'hard',
  "Curaçao code varies",
  "رمز كوراساو متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Côte d'Ivoire?",
  "ما هو رمز الفيفا لـ ساحل العاج？",
  "[\"Côte d'Ivoire\",\"Spain\",\"Austria\",\"Mexico\"]",
  "[\"ساحل العاج\",\"إسبانيا\",\"النمسا\",\"المكسيك\"]",
  0,
  'hard',
  "Côte d'Ivoire code varies",
  "رمز ساحل العاج متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Ecuador?",
  "ما هو رمز الفيفا لـ الإكوادور？",
  "[\"Ecuador\",\"Cabo Verde\",\"Jordan\",\"South Africa\"]",
  "[\"الإكوادور\",\"كابو فيردي\",\"الأردن\",\"جنوب أفريقيا\"]",
  0,
  'hard',
  "Ecuador code varies",
  "رمز الإكوادور متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Netherlands?",
  "ما هو رمز الفيفا لـ هولندا？",
  "[\"Netherlands\",\"Saudi Arabia\",\"Portugal\",\"Korea Republic\"]",
  "[\"هولندا\",\"السعودية\",\"البرتغال\",\"كوريا الجنوبية\"]",
  0,
  'hard',
  "Netherlands code varies",
  "رمز هولندا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Japan?",
  "ما هو رمز الفيفا لـ اليابان？",
  "[\"Japan\",\"Uruguay\",\"Colombia\",\"Czechia\"]",
  "[\"اليابان\",\"الأوروغواي\",\"كولومبيا\",\"التشيك\"]",
  0,
  'hard',
  "Japan code varies",
  "رمز اليابان متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Tunisia?",
  "ما هو رمز الفيفا لـ تونس？",
  "[\"Tunisia\",\"France\",\"Uzbekistan\",\"Canada\"]",
  "[\"تونس\",\"فرنسا\",\"أوزبكستان\",\"كندا\"]",
  0,
  'hard',
  "Tunisia code varies",
  "رمز تونس متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Sweden?",
  "ما هو رمز الفيفا لـ السويد？",
  "[\"Sweden\",\"Senegal\",\"Congo DR\",\"Bosnia and Herzegovina\"]",
  "[\"السويد\",\"السنغال\",\"الكونغو الديمقراطية\",\"البوسنة والهرسك\"]",
  0,
  'hard',
  "Sweden code varies",
  "رمز السويد متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Belgium?",
  "ما هو رمز الفيفا لـ بلجيكا？",
  "[\"Belgium\",\"Iraq\",\"England\",\"Qatar\"]",
  "[\"بلجيكا\",\"العراق\",\"إنجلترا\",\"قطر\"]",
  0,
  'hard',
  "Belgium code varies",
  "رمز بلجيكا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Egypt?",
  "ما هو رمز الفيفا لـ مصر？",
  "[\"Egypt\",\"Norway\",\"Croatia\",\"Switzerland\"]",
  "[\"مصر\",\"النرويج\",\"كرواتيا\",\"سويسرا\"]",
  0,
  'hard',
  "Egypt code varies",
  "رمز مصر متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for IR Iran?",
  "ما هو رمز الفيفا لـ إيران？",
  "[\"IR Iran\",\"Argentina\",\"Ghana\",\"Brazil\"]",
  "[\"إيران\",\"الأرجنتين\",\"غانا\",\"البرازيل\"]",
  0,
  'hard',
  "IR Iran code varies",
  "رمز إيران متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for New Zealand?",
  "ما هو رمز الفيفا لـ نيوزيلندا？",
  "[\"New Zealand\",\"Algeria\",\"Panama\",\"Morocco\"]",
  "[\"نيوزيلندا\",\"الجزائر\",\"بنما\",\"المغرب\"]",
  0,
  'hard',
  "New Zealand code varies",
  "رمز نيوزيلندا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Spain?",
  "ما هو رمز الفيفا لـ إسبانيا？",
  "[\"Spain\",\"Austria\",\"Mexico\",\"Haiti\"]",
  "[\"إسبانيا\",\"النمسا\",\"المكسيك\",\"هايتي\"]",
  0,
  'hard',
  "Spain code varies",
  "رمز إسبانيا متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc2026-teams'),
  "What is the FIFA code for Cabo Verde?",
  "ما هو رمز الفيفا لـ كابو فيردي？",
  "[\"Cabo Verde\",\"Jordan\",\"South Africa\",\"Scotland\"]",
  "[\"كابو فيردي\",\"الأردن\",\"جنوب أفريقيا\",\"اسكتلندا\"]",
  0,
  'hard',
  "Cabo Verde code varies",
  "رمز كابو فيردي متغير",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is a \"hat-trick\"?",
  "ما هي \"الهاتريك\"؟",
  "[\"3 goals by one player in a match\",\"3 consecutive wins\",\"3 saves by a goalkeeper\",\"3 penalties awarded\"]",
  "[\"3 أهداف للاعب واحد في مباراة\",\"3 انتصارات متتالية\",\"3 تصديات لحارس\",\"3 ركلات جزاء\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What does \"Clean sheet\" mean?",
  "ماذا يعني \"شباك نظيفة\"؟",
  "[\"Goalkeeper concedes no goals\",\"No fouls in the match\",\"Team wins without scoring\",\"Stadium is empty\"]",
  "[\"لم يستقبل حارس المرمى أي أهداف\",\"لا أخطاء في المباراة\",\"فريق يفوز دون تسجيل\",\"الملعب فارغ\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is a \"derby\" match?",
  "ما هي مباراة \"الديربي\"؟",
  "[\"Match between local rivals\",\"Match on a Wednesday\",\"Final match of the season\",\"Match with no goals\"]",
  "[\"مباراة بين غريمين محليين\",\"مباراة يوم الأربعاء\",\"المباراة النهائية للموسم\",\"مباراة بدون أهداف\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What does \"Tiki-taka\" describe?",
  "ماذا يصف \"تيكي تاكا\"؟",
  "[\"Short passing possession style\",\"Long ball tactic\",\"Defensive formation\",\"Counter-attack strategy\"]",
  "[\"أسلوب التمريرات القصيرة والاستحواذ\",\"تكتيك الكرات الطويلة\",\"تشكيل دفاعي\",\"استراتيجية الهجوم المرتد\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is a \"Catenaccio\" system?",
  "ما هو نظام \"كاتيناتشيو\"؟",
  "[\"Defensive Italian system\",\"Attacking Dutch system\",\"Brazilian samba style\",\"German pressing\"]",
  "[\"النظام الدفاعي الإيطالي\",\"النظام الهجومي الهولندي\",\"أسلوب السامبا البرازيلي\",\"الضغط الألماني\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is \"Total Football\"?",
  "ما هي \"كرة القدم الشاملة\"؟",
  "[\"Dutch system where players interchange positions\",\"All players must score\",\"No goalkeepers allowed\",\"11 strikers tactic\"]",
  "[\"النظام الهولندي حيث يتبادل اللاعبون المراكز\",\"جميع اللاعبين يجب أن يسجلوا\",\"لا يسمح بحراس المرمى\",\"تكتيك 11 مهاجماً\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What does \"Injury time\" mean?",
  "ماذا يعني \"الوقت بدل الضائع\"؟",
  "[\"Extra minutes added at end of half\",\"Time when players rest\",\"Time between seasons\",\"Warm-up period\"]",
  "[\"دقائق إضافية تضاف في نهاية الشوط\",\"وقت راحة اللاعبين\",\"الوقت بين المواسم\",\"فترة الإحماء\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is a \"Golden Goal\"?",
  "ما هو \"الهدف الذهبي\"؟",
  "[\"First goal in extra time wins the match\",\"Goal scored from midfield\",\"Goal in the final minute\",\"Goal that wins the league\"]",
  "[\"الهدف الأول في الوقت الإضافي يفوز بالمباراة\",\"هدف من منتصف الملعب\",\"هدف في الدقيقة الأخيرة\",\"هدف يفوز بالدوري\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is \"Gegenpressing\"?",
  "ما هو \"الغيغنبريسينغ\"؟",
  "[\"Counter-pressing immediately after losing the ball\",\"Pressing in opponent half\",\"Deep defending\",\"Slow build-up play\"]",
  "[\"الضغط مباشرة بعد فقدان الكرة\",\"الضغط في نصف الخصم\",\"دفاع عميق\",\"بناء هجومي بطيء\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'football-rules'),
  "What is a \"Panenka\" penalty?",
  "ما هي ركلة \"البانينكا\"؟",
  "[\"Chipped shot down the middle\",\"Hard shot to the corner\",\"Pass instead of shot\",\"Goalkeeper takes the kick\"]",
  "[\"تسديدة مقوسة في المنتصف\",\"تسديدة قوية للزاوية\",\"تمرير بدلاً من التسديد\",\"حارس المرمى يسدد\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 10 shirt?",
  "أي لاعب يرتدي القميص رقم 10؟",
  "[\"Victor Osimhen\",\"Riyad Mahrez\",\"Lionel Messi\",\"Kylian Mbappé\"]",
  "[\"فيكتور أوسيمين\",\"رياض محرز\",\"ليونيل ميسي\",\"كيليان مبابي\"]",
  2,
  'medium',
  "Lionel Messi wears #10.",
  "ليونيل ميسي يرتدي رقم 10.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 10?",
  "أي لاعب يلعب لـ 10？",
  "[\"Lionel Messi\",\"Robert Lewandowski\",\"Neymar Jr\",\"Diego Maradona\"]",
  "[\"ليونيل ميسي\",\"روبرت ليفاندوفسكي\",\"نيمار\",\"دييغو مارادونا\"]",
  0,
  'easy',
  "Lionel Messi plays for Argentina.",
  "ليونيل ميسي يلعب لـ Argentina.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 7 shirt?",
  "أي لاعب يرتدي القميص رقم 7؟",
  "[\"Cristiano Ronaldo\",\"Zinedine Zidane\",\"Diego Maradona\",\"Kylian Mbappé\"]",
  "[\"كريستيانو رونالدو\",\"زين الدين زيدان\",\"دييغو مارادونا\",\"كيليان مبابي\"]",
  0,
  'medium',
  "Cristiano Ronaldo wears #7.",
  "كريستيانو رونالدو يرتدي رقم 7.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 7?",
  "أي لاعب يلعب لـ 7？",
  "[\"Victor Osimhen\",\"Sadio Mané\",\"Achraf Hakimi\",\"Cristiano Ronaldo\"]",
  "[\"فيكتور أوسيمين\",\"ساديو ماني\",\"أشرف حكيمي\",\"كريستيانو رونالدو\"]",
  3,
  'easy',
  "Cristiano Ronaldo plays for Portugal.",
  "كريستيانو رونالدو يلعب لـ Portugal.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 11 shirt?",
  "أي لاعب يرتدي القميص رقم 11؟",
  "[\"Mohamed Salah\",\"Kevin De Bruyne\",\"Karim Benzema\",\"Pelé\"]",
  "[\"محمد صلاح\",\"كيفين دي بروين\",\"كريم بنزيما\",\"بيليه\"]",
  0,
  'medium',
  "Mohamed Salah wears #11.",
  "محمد صلاح يرتدي رقم 11.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 11?",
  "أي لاعب يلعب لـ 11？",
  "[\"Kylian Mbappé\",\"Kevin De Bruyne\",\"Xavi\",\"Mohamed Salah\"]",
  "[\"كيليان مبابي\",\"كيفين دي بروين\",\"تشافي\",\"محمد صلاح\"]",
  3,
  'easy',
  "Mohamed Salah plays for Egypt.",
  "محمد صلاح يلعب لـ Egypt.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 17 shirt?",
  "أي لاعب يرتدي القميص رقم 17؟",
  "[\"Kylian Mbappé\",\"Kevin De Bruyne\",\"Lionel Messi\",\"Cristiano Ronaldo\"]",
  "[\"كيليان مبابي\",\"كيفين دي بروين\",\"ليونيل ميسي\",\"كريستيانو رونالدو\"]",
  1,
  'medium',
  "Kevin De Bruyne wears #17.",
  "كيفين دي بروين يرتدي رقم 17.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 17?",
  "أي لاعب يلعب لـ 17？",
  "[\"Andrés Iniesta\",\"Kevin De Bruyne\",\"Luka Modrić\",\"Kylian Mbappé\"]",
  "[\"أندريس إنييستا\",\"كيفين دي بروين\",\"لوكا مودريتش\",\"كيليان مبابي\"]",
  1,
  'easy',
  "Kevin De Bruyne plays for Belgium.",
  "كيفين دي بروين يلعب لـ Belgium.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 9 shirt?",
  "أي لاعب يرتدي القميص رقم 9؟",
  "[\"Xavi\",\"Karim Benzema\",\"Diego Maradona\",\"Riyad Mahrez\"]",
  "[\"تشافي\",\"كريم بنزيما\",\"دييغو مارادونا\",\"رياض محرز\"]",
  1,
  'medium',
  "Karim Benzema wears #9.",
  "كريم بنزيما يرتدي رقم 9.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 9?",
  "أي لاعب يلعب لـ 9？",
  "[\"Karim Benzema\",\"Achraf Hakimi\",\"Kevin De Bruyne\",\"Luka Modrić\"]",
  "[\"كريم بنزيما\",\"أشرف حكيمي\",\"كيفين دي بروين\",\"لوكا مودريتش\"]",
  0,
  'easy',
  "Karim Benzema plays for France.",
  "كريم بنزيما يلعب لـ France.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 4 shirt?",
  "أي لاعب يرتدي القميص رقم 4؟",
  "[\"Achraf Hakimi\",\"Victor Osimhen\",\"Neymar Jr\",\"Sergio Ramos\"]",
  "[\"أشرف حكيمي\",\"فيكتور أوسيمين\",\"نيمار\",\"سيرخيو راموس\"]",
  3,
  'medium',
  "Sergio Ramos wears #4.",
  "سيرخيو راموس يرتدي رقم 4.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 4?",
  "أي لاعب يلعب لـ 4？",
  "[\"Lionel Messi\",\"Karim Benzema\",\"Sadio Mané\",\"Sergio Ramos\"]",
  "[\"ليونيل ميسي\",\"كريم بنزيما\",\"ساديو ماني\",\"سيرخيو راموس\"]",
  3,
  'easy',
  "Sergio Ramos plays for Spain.",
  "سيرخيو راموس يلعب لـ Spain.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 8 shirt?",
  "أي لاعب يرتدي القميص رقم 8؟",
  "[\"Xavi\",\"Lionel Messi\",\"Victor Osimhen\",\"Andrés Iniesta\"]",
  "[\"تشافي\",\"ليونيل ميسي\",\"فيكتور أوسيمين\",\"أندريس إنييستا\"]",
  3,
  'medium',
  "Andrés Iniesta wears #8.",
  "أندريس إنييستا يرتدي رقم 8.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 8?",
  "أي لاعب يلعب لـ 8？",
  "[\"Kevin De Bruyne\",\"Iker Casillas\",\"Robert Lewandowski\",\"Andrés Iniesta\"]",
  "[\"كيفين دي بروين\",\"إيكر كاسياس\",\"روبرت ليفاندوفسكي\",\"أندريس إنييستا\"]",
  3,
  'easy',
  "Andrés Iniesta plays for Spain.",
  "أندريس إنييستا يلعب لـ Spain.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 6 shirt?",
  "أي لاعب يرتدي القميص رقم 6؟",
  "[\"Xavi\",\"Lionel Messi\",\"Achraf Hakimi\",\"Hakim Ziyech\"]",
  "[\"تشافي\",\"ليونيل ميسي\",\"أشرف حكيمي\",\"حكيم زياش\"]",
  0,
  'medium',
  "Xavi wears #6.",
  "تشافي يرتدي رقم 6.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 6?",
  "أي لاعب يلعب لـ 6？",
  "[\"Kylian Mbappé\",\"Sergio Ramos\",\"Mohamed Salah\",\"Xavi\"]",
  "[\"كيليان مبابي\",\"سيرخيو راموس\",\"محمد صلاح\",\"تشافي\"]",
  3,
  'easy',
  "Xavi plays for Spain.",
  "تشافي يلعب لـ Spain.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 1 shirt?",
  "أي لاعب يرتدي القميص رقم 1؟",
  "[\"Andrés Iniesta\",\"Xavi\",\"Manuel Neuer\",\"Luka Modrić\"]",
  "[\"أندريس إنييستا\",\"تشافي\",\"مانويل نوير\",\"لوكا مودريتش\"]",
  2,
  'medium',
  "Manuel Neuer wears #1.",
  "مانويل نوير يرتدي رقم 1.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 1?",
  "أي لاعب يلعب لـ 1？",
  "[\"Gianluigi Buffon\",\"Victor Osimhen\",\"Xavi\",\"Manuel Neuer\"]",
  "[\"جيانلويجي بوفون\",\"فيكتور أوسيمين\",\"تشافي\",\"مانويل نوير\"]",
  3,
  'easy',
  "Manuel Neuer plays for Germany.",
  "مانويل نوير يلعب لـ Germany.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player wears the number 2 shirt?",
  "أي لاعب يرتدي القميص رقم 2؟",
  "[\"Achraf Hakimi\",\"Xavi\",\"Lionel Messi\",\"Mohamed Salah\"]",
  "[\"أشرف حكيمي\",\"تشافي\",\"ليونيل ميسي\",\"محمد صلاح\"]",
  0,
  'medium',
  "Achraf Hakimi wears #2.",
  "أشرف حكيمي يرتدي رقم 2.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-player'),
  "Which player plays for 2?",
  "أي لاعب يلعب لـ 2？",
  "[\"Achraf Hakimi\",\"Lionel Messi\",\"Gianluigi Buffon\",\"Neymar Jr\"]",
  "[\"أشرف حكيمي\",\"ليونيل ميسي\",\"جيانلويجي بوفون\",\"نيمار\"]",
  0,
  'easy',
  "Achraf Hakimi plays for Morocco.",
  "أشرف حكيمي يلعب لـ Morocco.",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most World Cup goals in a single tournament?",
  "ما هو الرقم القياسي لـ: Most World Cup goals in a single tournament？",
  "[\"Just Fontaine (13 in 1958)\",\"Ronaldo (8 in 2002)\",\"Thomas Müller (5 in 2010)\",\"Mbappé (8 in 2022)\"]",
  "[\"جوست فونتين (13 في 1958)\",\"رونالدو (8 في 2002)\",\"توماس مولر (5 في 2010)\",\"مبابي (8 في 2022)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most goals in a single World Cup match?",
  "ما هو الرقم القياسي لـ: Most goals in a single World Cup match？",
  "[\"12 (Austria 7-5 Switzerland 1954)\",\"10 (Hungary 10-1 El Salvador)\",\"9 (Brazil 6-3 Poland)\",\"8 (Germany 8-0 Saudi Arabia)\"]",
  "[\"12 (النمسا 7-5 سويسرا 1954)\",\"10 (المجر 10-1 السلفادور)\",\"9 (البرازيل 6-3 بولندا)\",\"8 (ألمانيا 8-0 السعودية)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most World Cup clean sheets (goalkeeper)?",
  "ما هو الرقم القياسي لـ: Most World Cup clean sheets (goalkeeper)？",
  "[\"Iker Casillas (8 in 2010)\",\"Gianluigi Buffon (5 in 2006)\",\"Manuel Neuer (4 in 2014)\",\"Fabien Barthez (5 in 1998)\"]",
  "[\"إيكر كاسياس (8 في 2010)\",\"جيانلويجي بوفون (5 في 2006)\",\"مانويل نوير (4 في 2014)\",\"فابيان بارتيز (5 في 1998)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Oldest player to score in a World Cup?",
  "ما هو الرقم القياسي لـ: Oldest player to score in a World Cup？",
  "[\"Roger Milla (42 years, 1994)\",\"Pelé (17 years, 1958)\",\"Miroslav Klose (36, 2014)\",\"Lionel Messi (35, 2022)\"]",
  "[\"روجر ميلا (42 عاماً، 1994)\",\"بيليه (17 عاماً، 1958)\",\"ميروسلاف كلوزه (36، 2014)\",\"ليونيل ميسي (35، 2022)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Youngest player to play in a World Cup?",
  "ما هو الرقم القياسي لـ: Youngest player to play in a World Cup？",
  "[\"Norman Whiteside (17 years, 1982)\",\"Pelé (17, 1958)\",\"Mbappé (19, 2018)\",\"Messi (18, 2006)\"]",
  "[\"نورمان وايتسايد (17 عاماً، 1982)\",\"بيليه (17، 1958)\",\"مبابي (19، 2018)\",\"ميسي (18، 2006)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Largest World Cup win margin?",
  "ما هو الرقم القياسي لـ: Largest World Cup win margin？",
  "[\"Hungary 9-0 South Korea (1954), Yugoslavia 9-0 Zaire (1974), Hungary 10-1 El Salvador (1982)\",\"Brazil 8-0 Sweden (1950)\",\"Germany 8-0 Saudi Arabia (2002)\",\"Portugal 7-0 North Korea (2010)\"]",
  "[\"المجر 9-0 كوريا الجنوبية (1954)، يوغوسلافيا 9-0 زائير (1974)، المجر 10-1 السلفادور (1982)\",\"البرازيل 8-0 السويد (1950)\",\"ألمانيا 8-0 السعودية (2002)\",\"البرتغال 7-0 كوريا الشمالية (2010)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most consecutive World Cup wins?",
  "ما هو الرقم القياسي لـ: Most consecutive World Cup wins？",
  "[\"Brazil (11 matches, 1998-2006)\",\"Germany (7 matches)\",\"Argentina (6 matches)\",\"France (5 matches)\"]",
  "[\"البرازيل (11 مباراة، 1998-2006)\",\"ألمانيا (7 مباريات)\",\"الأرجنتين (6 مباريات)\",\"فرنسا (5 مباريات)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most goals by a defender in World Cup history?",
  "ما هو الرقم القياسي لـ: Most goals by a defender in World Cup history？",
  "[\"Paolo Maldini (4 goals)\",\"Sergio Ramos (3 goals)\",\"Cafu (2 goals)\",\"Roberto Carlos (1 goal)\"]",
  "[\"باولو مالديني (4 أهداف)\",\"سيرخيو راموس (3 أهداف)\",\"كافو (هدفان)\",\"روبرتو كارلوس (هدف)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Fastest red card in World Cup history?",
  "ما هو الرقم القياسي لـ: Fastest red card in World Cup history？",
  "[\"José Batista (56 seconds, 1986)\",\"Zinedine Zidane (110 min, 2006)\",\"Rigobert Song (68 min, 1994)\",\"David Beckham (47 min, 1998)\"]",
  "[\"خوسيه باتيستا (56 ثانية، 1986)\",\"زين الدين زيدان (110 د، 2006)\",\"ريغوبرت سونغ (68 د، 1994)\",\"ديفيد بيكهام (47 د، 1998)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'wc-history'),
  "What is the record for: Most players from one club in a World Cup squad?",
  "ما هو الرقم القياسي لـ: Most players from one club in a World Cup squad？",
  "[\"Bayern Munich (8 in 2014)\",\"Real Madrid (7 in 2022)\",\"Barcelona (6 in 2010)\",\"Manchester City (6 in 2022)\"]",
  "[\"بايرن ميونخ (8 في 2014)\",\"ريال مدريد (7 في 2022)\",\"برشلونة (6 في 2010)\",\"مانشستر سيتي (6 في 2022)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Tehran?",
  "أي ملعب يقع في Tehran, Iran？",
  "[\"Bukit Jalil\",\"Stamford Bridge\",\"Estádio do Morumbi\",\"Azadi Stadium\"]",
  "[\"بوكيت جليل\",\"ستامفورد بريدج\",\"ملعب دو مورومبي\",\"ملعب آزادي\"]",
  3,
  'medium',
  "Azadi Stadium: Tehran, Iran (78,000)",
  "ملعب آزادي: طهران، إيران (78,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Kuala Lumpur?",
  "أي ملعب يقع في Kuala Lumpur, Malaysia？",
  "[\"Bukit Jalil\",\"Mineirão\",\"Estadio Monumental\",\"Stamford Bridge\"]",
  "[\"بوكيت جليل\",\"مينيراو\",\"ملعب مونومنتال\",\"ستامفورد بريدج\"]",
  0,
  'medium',
  "Bukit Jalil: Kuala Lumpur, Malaysia (87,000)",
  "بوكيت جليل: كوالالمبور، ماليزيا (87,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Jakarta?",
  "أي ملعب يقع في Jakarta, Indonesia？",
  "[\"Gelora Bung Karno\",\"Feijenoord Stadion (De Kuip)\",\"Estádio José Alvalade\",\"Azadi Stadium\"]",
  "[\"غلورا بونغ كارنو\",\"ملعب فيينورد (دي كويب)\",\"ملعب جوزيه ألفالادي\",\"ملعب آزادي\"]",
  0,
  'medium',
  "Gelora Bung Karno: Jakarta, Indonesia (77,000)",
  "غلورا بونغ كارنو: جاكرتا، إندونيسيا (77,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Ahmedabad?",
  "أي ملعب يقع في Ahmedabad, India？",
  "[\"Tottenham Hotspur Stadium\",\"Rungrado 1st of May\",\"Al Janoub Stadium\",\"Narendra Modi Stadium\"]",
  "[\"ملعب توتنهام\",\"ملعب رونغرادو\",\"ملعب الجنوب\",\"ملعب ناريندرا مودي\"]",
  3,
  'medium',
  "Narendra Modi Stadium: Ahmedabad, India (132,000)",
  "ملعب ناريندرا مودي: أحمد آباد، الهند (132,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Pyongyang?",
  "أي ملعب يقع في Pyongyang, North Korea？",
  "[\"Rungrado 1st of May\",\"Etihad Stadium\",\"Mineirão\",\"Khalifa International Stadium\"]",
  "[\"ملعب رونغرادو\",\"ملعب الاتحاد\",\"مينيراو\",\"ملعب خليفة الدولي\"]",
  0,
  'medium',
  "Rungrado 1st of May: Pyongyang, North Korea (114,000)",
  "ملعب رونغرادو: بيونغيانغ، كوريا الشمالية (114,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Lima?",
  "أي ملعب يقع في Lima, Peru？",
  "[\"Estadio Monumental\",\"Mineirão\",\"Stade Vélodrome\",\"Azadi Stadium\"]",
  "[\"ملعب مونومنتال\",\"مينيراو\",\"ملعب فيلودروم\",\"ملعب آزادي\"]",
  0,
  'medium',
  "Estadio Monumental: Lima, Peru (80,000)",
  "ملعب مونومنتال: ليما، بيرو (80,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Montevideo?",
  "أي ملعب يقع في Montevideo, Uruguay？",
  "[\"Estadio Centenario\",\"Azadi Stadium\",\"Arena Corinthians\",\"Etihad Stadium\"]",
  "[\"ملعب سنتيناريو\",\"ملعب آزادي\",\"أرينا كورينثيانز\",\"ملعب الاتحاد\"]",
  0,
  'medium',
  "Estadio Centenario: Montevideo, Uruguay (60,000)",
  "ملعب سنتيناريو: مونتيفيديو، الأوروغواي (60,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Buenos Aires?",
  "أي ملعب يقع في Buenos Aires, Argentina？",
  "[\"Azadi Stadium\",\"La Bombonera\",\"Estadio Centenario\",\"Tottenham Hotspur Stadium\"]",
  "[\"ملعب آزادي\",\"لا بومبونيرا\",\"ملعب سنتيناريو\",\"ملعب توتنهام\"]",
  1,
  'medium',
  "La Bombonera: Buenos Aires, Argentina (54,000)",
  "لا بومبونيرا: بوينس آيرس، الأرجنتين (54,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in São Paulo?",
  "أي ملعب يقع في São Paulo, Brazil？",
  "[\"Estádio do Morumbi\",\"Bukit Jalil\",\"Estádio da Luz\",\"Rungrado 1st of May\"]",
  "[\"ملعب دو مورومبي\",\"بوكيت جليل\",\"ملعب النور\",\"ملعب رونغرادو\"]",
  0,
  'medium',
  "Estádio do Morumbi: São Paulo, Brazil (67,000)",
  "ملعب دو مورومبي: ساو باولو، البرازيل (67,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Belo Horizonte?",
  "أي ملعب يقع في Belo Horizonte, Brazil？",
  "[\"La Bombonera\",\"Narendra Modi Stadium\",\"Mineirão\",\"Azadi Stadium\"]",
  "[\"لا بومبونيرا\",\"ملعب ناريندرا مودي\",\"مينيراو\",\"ملعب آزادي\"]",
  2,
  'medium',
  "Mineirão: Belo Horizonte, Brazil (62,000)",
  "مينيراو: بيلو هوريزونتي، البرازيل (62,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'stadiums'),
  "Which stadium is in Porto Alegre?",
  "أي ملعب يقع في Porto Alegre, Brazil？",
  "[\"Azadi Stadium\",\"Al Janoub Stadium\",\"Estádio Beira-Rio\",\"Education City Stadium\"]",
  "[\"ملعب آزادي\",\"ملعب الجنوب\",\"ملعب بيرا ريو\",\"ملعب المدينة التعليمية\"]",
  2,
  'medium',
  "Estádio Beira-Rio: Porto Alegre, Brazil (50,000)",
  "ملعب بيرا ريو: بورتو أليغري، البرازيل (50,000)",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "Which Arab team has qualified for the 2026 World Cup?",
  "أي منتخب عربي تأهل لكأس العالم 2026؟",
  "[\"Morocco, Tunisia, Egypt, Algeria, Saudi Arabia, Jordan, Qatar\",\"Only Morocco and Saudi Arabia\",\"All Arab teams\",\"None\"]",
  "[\"المغرب، تونس، مصر، الجزائر، السعودية، الأردن، قطر\",\"فقط المغرب والسعودية\",\"جميع المنتخبات العربية\",\"لا أحد\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "Which Arab goalkeeper is known as the best in history?",
  "من هو أفضل حارس مرمى عربي في التاريخ؟",
  "[\"Essam El-Hadary (Egypt)\",\"Nawaf Al-Aqidi (Saudi Arabia)\",\"Farouk Ben Mustapha (Tunisia)\",\"Bono (Morocco)\"]",
  "[\"عصام الحضري (مصر)\",\"نواف العقيدي (السعودية)\",\"فاروق بن مصطفى (تونس)\",\"بونو (المغرب)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "How many World Cups have Egypt qualified for?",
  "كم عدد كؤوس العالم التي تأهلت لها مصر؟",
  "[\"3 (1934, 1990, 2018)\",\"2\",\"4\",\"1\"]",
  "[\"3 (1934، 1990، 2018)\",\"2\",\"4\",\"1\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "Which Arab team has the best FIFA ranking?",
  "أي منتخب عربي لديه أفضل تصنيف فيفا؟",
  "[\"Morocco (top 15)\",\"Tunisia (top 30)\",\"Egypt (top 30)\",\"Algeria (top 40)\"]",
  "[\"المغرب (أفضل 15)\",\"تونس (أفضل 30)\",\"مصر (أفضل 30)\",\"الجزائر (أفضل 40)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "Who is Morocco's all-time top scorer?",
  "من هو هداف المغرب التاريخي؟",
  "[\"Ahmed Faras (42 goals)\",\"Hakim Ziyech (22 goals)\",\"Mustapha Hadji (13 goals)\",\"Achraf Hakimi (9 goals)\"]",
  "[\"أحمد فرس (42 هدفاً)\",\"حكيم زياش (22 هدفاً)\",\"مصطفى حاجي (13 هدفاً)\",\"أشرف حكيمي (9 أهداف)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'arab-teams'),
  "Who is Egypt's all-time top scorer?",
  "من هو هداف مصر التاريخي؟",
  "[\"Hossam Hassan (68 goals)\",\"Mohamed Salah (55 goals)\",\"Ahmed Hassan (33 goals)\",\"Mahmoud El Khatib (28 goals)\"]",
  "[\"حسام حسن (68 هدفاً)\",\"محمد صلاح (55 هدفاً)\",\"أحمد حسن (33 هدفاً)\",\"محمود الخطيب (28 هدفاً)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'african-teams'),
  "Who is Senegal's all-time top scorer?",
  "من هو هداف السنغال التاريخي؟",
  "[\"Sadio Mané (40+ goals)\",\"El Hadji Diouf (22 goals)\",\"Henri Camara (19 goals)\",\"Mamadou Niang (18 goals)\"]",
  "[\"ساديو ماني (40+ هدفاً)\",\"الحاج ضيوف (22 هدفاً)\",\"هنري كمارا (19 هدفاً)\",\"مامادو نيانغ (18 هدفاً)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'african-teams'),
  "Which African team has the best defensive record in WC?",
  "أي منتخب أفريقي لديه أفضل سجل دفاعي في كأس العالم؟",
  "[\"Morocco (conceded 1 goal in 2022 WC)\",\"Nigeria (2 goals in 1994)\",\"Cameroon (3 goals in 1990)\",\"Senegal (3 goals in 2002)\"]",
  "[\"المغرب (استقبل هدفاً واحداً في 2022)\",\"نيجيريا (هدفان في 1994)\",\"الكاميرون (3 أهداف في 1990)\",\"السنغال (3 أهداف في 2002)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'african-teams'),
  "Which African nation has won the most AFCON titles?",
  "أي دولة أفريقية فازت بأكبر عدد من ألقاب كأس أمم أفريقيا؟",
  "[\"Egypt (7)\",\"Cameroon (5)\",\"Nigeria (3)\",\"Algeria (2)\"]",
  "[\"مصر (7)\",\"الكاميرون (5)\",\"نيجيريا (3)\",\"الجزائر (2)\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'african-teams'),
  "Who scored the most goals in AFCON history?",
  "من سجل أكبر عدد من الأهداف في تاريخ كأس أمم أفريقيا؟",
  "[\"Samuel Eto'o (18 goals)\",\"Didier Drogba (11 goals)\",\"Mohamed Salah (6 goals)\",\"Asamoah Gyan (6 goals)\"]",
  "[\"صامويل إيتو (18 هدفاً)\",\"ديدييه دروغبا (11 هدفاً)\",\"محمد صلاح (6 أهداف)\",\"أسامواه جيان (6 أهداف)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'european-teams'),
  "Which European country has won the most EURO titles?",
  "أي دولة أوروبية فازت بأكبر عدد من ألقاب اليورو؟",
  "[\"Spain (4)\",\"Germany (3)\",\"France (2)\",\"Italy (2)\"]",
  "[\"إسبانيا (4)\",\"ألمانيا (3)\",\"فرنسا (2)\",\"إيطاليا (2)\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'european-teams'),
  "Which European club has the most UCL titles?",
  "أي نادٍ أوروبي لديه أكبر عدد من ألقاب دوري الأبطال？",
  "[\"Real Madrid (15)\",\"AC Milan (7)\",\"Bayern Munich (6)\",\"Liverpool (6)\"]",
  "[\"ريال مدريد (15)\",\"ميلان (7)\",\"بايرن ميونخ (6)\",\"ليفربول (6)\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'european-teams'),
  "Which European league is known as the Premier League?",
  "أي دوري أوروبي يُعرف بالدوري الإنجليزي الممتاز؟",
  "[\"England\",\"Scotland\",\"Spain\",\"Germany\"]",
  "[\"إنجلترا\",\"اسكتلندا\",\"إسبانيا\",\"ألمانيا\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'european-teams'),
  "What is the name of the European club competition?",
  "ما اسم بطولة الأندية الأوروبية؟",
  "[\"UEFA Champions League\",\"Europa League\",\"European Cup\",\"Euro League\"]",
  "[\"دوري أبطال أوروبا\",\"الدوري الأوروبي\",\"الكأس الأوروبية\",\"اليورو ليغ\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "Who is Brazil's all-time top scorer?",
  "من هو هداف البرازيل التاريخي؟",
  "[\"Neymar (79 goals)\",\"Pelé (77 goals)\",\"Ronaldo (62 goals)\",\"Romário (55 goals)\"]",
  "[\"نيمار (79 هدفاً)\",\"بيليه (77 هدفاً)\",\"رونالدو (62 هدفاً)\",\"روماريو (55 هدفاً)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "How many times has Brazil won the World Cup?",
  "كم مرة فازت البرازيل بكأس العالم؟",
  "[\"5\",\"4\",\"3\",\"2\"]",
  "[\"5\",\"4\",\"3\",\"2\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'south-american-teams'),
  "Which Brazilian player has won 3 World Cups?",
  "أي لاعب برازيلي فاز بـ 3 كؤوس عالم？",
  "[\"Pelé (1958, 1962, 1970)\",\"Ronaldo (1994, 2002)\",\"Neymar (0)\",\"Cafu (1994, 2002)\"]",
  "[\"بيليه (1958، 1962، 1970)\",\"رونالدو (1994، 2002)\",\"نيمار (0)\",\"كافو (1994، 2002)\"]",
  0,
  'easy',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'asian-teams'),
  "How many times has Japan won the AFC Asian Cup?",
  "كم مرة فازت اليابان بكأس آسيا؟",
  "[\"4 (1992, 2000, 2004, 2011)\",\"3\",\"2\",\"1\"]",
  "[\"4 (1992، 2000، 2004، 2011)\",\"3\",\"2\",\"1\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'asian-teams'),
  "Which Australian player has scored the most WC goals?",
  "أي لاعب أسترالي سجل أكبر عدد من الأهداف في كأس العالم？",
  "[\"Tim Cahill (5 goals)\",\"Mark Viduka (3 goals)\",\"Harry Kewell (2 goals)\",\"John Aloisi (2 goals)\"]",
  "[\"تيم كاهيل (5 أهداف)\",\"مارك فيدوكا (3 أهداف)\",\"هاري كيويل (هدفان)\",\"جون ألويسي (هدفان)\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'asian-teams'),
  "Which Asian team has the highest FIFA ranking?",
  "أي منتخب آسيوي لديه أعلى تصنيف فيفا؟",
  "[\"Japan\",\"South Korea\",\"Australia\",\"Iran\"]",
  "[\"اليابان\",\"كوريا الجنوبية\",\"أستراليا\",\"إيران\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'lebanese-fan-culture'),
  "Who is Lebanon's all-time top scorer?",
  "من هو هداف لبنان التاريخي؟",
  "[\"Hassan Maatouk (23 goals)\",\"Roda Antar (20 goals)\",\"Vardan Ghazaryan (18 goals)\",\"Youssef Mohamad (16 goals)\"]",
  "[\"حسن معتوق (23 هدفاً)\",\"رضا عنتر (20 هدفاً)\",\"فاردان غازاريان (18 هدفاً)\",\"يوسف محمد (16 هدفاً)\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'lebanese-fan-culture'),
  "Which club is based in Tripoli, Lebanon?",
  "أي نادٍ مقره طرابلس، لبنان؟",
  "[\"Salam Zgharta\",\"Al-Ansar\",\"Nejmeh\",\"Al-Ahed\"]",
  "[\"سلام زغرتا\",\"الأنصار\",\"النجمة\",\"العهد\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'lebanese-fan-culture'),
  "What is the capacity of Camille Chamoun Stadium?",
  "ما هي سعة ملعب كميل شمعون؟",
  "[\"~57,000\",\"~40,000\",\"~70,000\",\"~30,000\"]",
  "[\"~57,000\",\"~40,000\",\"~70,000\",\"~30,000\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'lebanese-fan-culture'),
  "Which year was Nejmeh SC founded?",
  "في أي سنة تأسس نادي النجمة؟",
  "[\"1945\",\"1933\",\"1951\",\"1966\"]",
  "[\"1945\",\"1933\",\"1951\",\"1966\"]",
  0,
  'medium',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'lebanese-fan-culture'),
  "What is the winter break period in Lebanese football?",
  "ما هي فترة العطلة الشتوية في كرة القدم اللبنانية؟",
  "[\"December to February\",\"November to December\",\"January only\",\"No winter break\"]",
  "[\"ديسمبر إلى فبراير\",\"نوفمبر إلى ديسمبر\",\"يناير فقط\",\"لا توجد عطلة شتوية\"]",
  0,
  'hard',
  "",
  "",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red, green, white, black horizontal\"?",
  "أي علم يوصف بأنه: \"أحمر، أخضر، أبيض، أسود أفقي\"؟",
  "[\"United Arab Emirates\",\"Kuwait\",\"Czech Republic\",\"Oman\"]",
  "[\"الإمارات العربية المتحدة\",\"الكويت\",\"جمهورية التشيك\",\"عُمان\"]",
  0,
  'medium',
  "Flag of United Arab Emirates",
  "علم الإمارات العربية المتحدة",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Green, white, red, black with trapezoid\"?",
  "أي علم يوصف بأنه: \"أخضر، أبيض، أحمر، أسود مع شبه منحرف\"؟",
  "[\"United Arab Emirates\",\"Yemen\",\"Kuwait\",\"Finland\"]",
  "[\"الإمارات العربية المتحدة\",\"اليمن\",\"الكويت\",\"فنلندا\"]",
  2,
  'medium',
  "Flag of Kuwait",
  "علم الكويت",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red, white, green horizontal with emblem\"?",
  "أي علم يوصف بأنه: \"أحمر، أبيض، أخضر أفقي مع شعار\"؟",
  "[\"Oman\",\"Kuwait\",\"Bahrain\",\"United Arab Emirates\"]",
  "[\"عُمان\",\"الكويت\",\"البحرين\",\"الإمارات العربية المتحدة\"]",
  0,
  'medium',
  "Flag of Oman",
  "علم عُمان",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red with white serrated edge\"?",
  "أي علم يوصف بأنه: \"أحمر مع حافة بيضاء مسننة\"؟",
  "[\"Saudi Arabia\",\"United Arab Emirates\",\"Czech Republic\",\"Bahrain\"]",
  "[\"السعودية\",\"الإمارات العربية المتحدة\",\"جمهورية التشيك\",\"البحرين\"]",
  3,
  'medium',
  "Flag of Bahrain",
  "علم البحرين",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red, white, red horizontal with green cedar\"?",
  "أي علم يوصف بأنه: \"أحمر، أبيض، أحمر أفقي مع أرزة خضراء\"؟",
  "[\"Lebanon\",\"Oman\",\"Ireland\",\"Bahrain\"]",
  "[\"لبنان\",\"عُمان\",\"أيرلندا\",\"البحرين\"]",
  0,
  'medium',
  "Flag of Lebanon",
  "علم لبنان",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red, white, black horizontal with two green stars\"?",
  "أي علم يوصف بأنه: \"أحمر، أبيض، أسود أفقي مع نجمتين أخضرتين\"؟",
  "[\"Finland\",\"United Arab Emirates\",\"Syria\",\"Yemen\"]",
  "[\"فنلندا\",\"الإمارات العربية المتحدة\",\"سوريا\",\"اليمن\"]",
  2,
  'medium',
  "Flag of Syria",
  "علم سوريا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Black, white, green horizontal with red triangle\"?",
  "أي علم يوصف بأنه: \"أسود، أبيض، أخضر أفقي مع مثلث أحمر\"؟",
  "[\"Oman\",\"Russia\",\"Palestine\",\"Kuwait\"]",
  "[\"عُمان\",\"روسيا\",\"فلسطين\",\"الكويت\"]",
  2,
  'medium',
  "Flag of Palestine",
  "علم فلسطين",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red, white, black horizontal stripes\"?",
  "أي علم يوصف بأنه: \"أحمر، أبيض، أسود خطوط أفقية\"؟",
  "[\"Yemen\",\"Ireland\",\"Saudi Arabia\",\"United Arab Emirates\"]",
  "[\"اليمن\",\"أيرلندا\",\"السعودية\",\"الإمارات العربية المتحدة\"]",
  0,
  'medium',
  "Flag of Yemen",
  "علم اليمن",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red with blue and white cross\"?",
  "أي علم يوصف بأنه: \"أحمر مع صليب أزرق وأبيض\"؟",
  "[\"Norway\",\"Denmark\",\"Czech Republic\",\"Ireland\"]",
  "[\"النرويج\",\"الدنمارك\",\"جمهورية التشيك\",\"أيرلندا\"]",
  0,
  'medium',
  "Flag of Norway",
  "علم النرويج",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Red with white cross\"?",
  "أي علم يوصف بأنه: \"أحمر مع صليب أبيض\"؟",
  "[\"Denmark\",\"Ireland\",\"Russia\",\"Czech Republic\"]",
  "[\"الدنمارك\",\"أيرلندا\",\"روسيا\",\"جمهورية التشيك\"]",
  0,
  'medium',
  "Flag of Denmark",
  "علم الدنمارك",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"White with blue cross\"?",
  "أي علم يوصف بأنه: \"أبيض مع صليب أزرق\"؟",
  "[\"Finland\",\"Russia\",\"Ireland\",\"Saudi Arabia\"]",
  "[\"فنلندا\",\"روسيا\",\"أيرلندا\",\"السعودية\"]",
  0,
  'hard',
  "Flag of Finland",
  "علم فنلندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Blue with red and white cross\"?",
  "أي علم يوصف بأنه: \"أزرق مع صليب أحمر وأبيض\"؟",
  "[\"Finland\",\"Palestine\",\"Iceland\",\"Syria\"]",
  "[\"فنلندا\",\"فلسطين\",\"آيسلندا\",\"سوريا\"]",
  2,
  'hard',
  "Flag of Iceland",
  "علم آيسلندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Green, white, orange vertical stripes\"?",
  "أي علم يوصف بأنه: \"أخضر، أبيض، برتقالي خطوط عمودية\"؟",
  "[\"United Arab Emirates\",\"Poland\",\"Ireland\",\"South Korea\"]",
  "[\"الإمارات العربية المتحدة\",\"بولندا\",\"أيرلندا\",\"كوريا الجنوبية\"]",
  2,
  'hard',
  "Flag of Ireland",
  "علم أيرلندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Blue and white stripes with white cross\"?",
  "أي علم يوصف بأنه: \"أزرق وأبيض خطوط مع صليب أبيض\"؟",
  "[\"Bahrain\",\"Finland\",\"North Korea\",\"Greece\"]",
  "[\"البحرين\",\"فنلندا\",\"كوريا الشمالية\",\"اليونان\"]",
  3,
  'hard',
  "Flag of Greece",
  "علم اليونان",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"White on top, red on bottom horizontal\"?",
  "أي علم يوصف بأنه: \"أبيض فوق أحمر أفقي\"؟",
  "[\"Czech Republic\",\"United Arab Emirates\",\"Saudi Arabia\",\"Poland\"]",
  "[\"جمهورية التشيك\",\"الإمارات العربية المتحدة\",\"السعودية\",\"بولندا\"]",
  3,
  'hard',
  "Flag of Poland",
  "علم بولندا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"White, blue, red horizontal stripes\"?",
  "أي علم يوصف بأنه: \"أبيض، أزرق، أحمر خطوط أفقية\"؟",
  "[\"Kuwait\",\"Yemen\",\"Russia\",\"United Arab Emirates\"]",
  "[\"الكويت\",\"اليمن\",\"روسيا\",\"الإمارات العربية المتحدة\"]",
  2,
  'hard',
  "Flag of Russia",
  "علم روسيا",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Blue triangle with white and red stripes\"?",
  "أي علم يوصف بأنه: \"مثلث أزرق مع خطوط بيضاء وحمراء\"؟",
  "[\"Czech Republic\",\"Yemen\",\"Denmark\",\"North Korea\"]",
  "[\"جمهورية التشيك\",\"اليمن\",\"الدنمارك\",\"كوريا الشمالية\"]",
  0,
  'hard',
  "Flag of Czech Republic",
  "علم جمهورية التشيك",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"White with red and blue circle\"?",
  "أي علم يوصف بأنه: \"أبيض مع دائرة حمراء وزرقاء\"؟",
  "[\"South Korea\",\"Oman\",\"Denmark\",\"Syria\"]",
  "[\"كوريا الجنوبية\",\"عُمان\",\"الدنمارك\",\"سوريا\"]",
  0,
  'hard',
  "Flag of South Korea",
  "علم كوريا الجنوبية",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Blue, red, blue horizontal with white circle and red star\"?",
  "أي علم يوصف بأنه: \"أزرق، أحمر، أزرق أفقي مع دائرة بيضاء ونجمة حمراء\"؟",
  "[\"United Arab Emirates\",\"North Korea\",\"Ireland\",\"Lebanon\"]",
  "[\"الإمارات العربية المتحدة\",\"كوريا الشمالية\",\"أيرلندا\",\"لبنان\"]",
  1,
  'hard',
  "Flag of North Korea",
  "علم كوريا الشمالية",
  true),
((SELECT id FROM quiz_categories WHERE slug = 'guess-flag'),
  "Which flag is described as: \"Green with white inscription and sword\"?",
  "أي علم يوصف بأنه: \"أخضر مع كتابة بيضاء وسيف\"؟",
  "[\"Palestine\",\"Saudi Arabia\",\"Ireland\",\"South Korea\"]",
  "[\"فلسطين\",\"السعودية\",\"أيرلندا\",\"كوريا الجنوبية\"]",
  1,
  'hard',
  "Flag of Saudi Arabia",
  "علم السعودية",
  true);
