/// <reference lib="webworker" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

type PushPayload = { title?: string; body?: string; tag?: string; url?: string };
type NotificationData = { url?: string };
type NotificationOptionsWithVibrate = NotificationOptions & { vibrate?: number[] };

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Runtime caching for Supabase API (NetworkFirst with timeout)
registerRoute(
  /^https?:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 10,
  })
);

// Runtime caching for Supabase Storage (CacheFirst)
registerRoute(
  /^https?:\/\/.*\.supabase\.co\/storage\/v1\/.*/i,
  new CacheFirst({
    cacheName: 'supabase-storage-cache',
  })
);

// Cache Google Fonts
registerRoute(
  /^https?:\/\/fonts\.(googleapis|gstatic)\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-cache',
  })
);

// Cache images
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/i,
  new CacheFirst({
    cacheName: 'image-cache',
  })
);

// Push notification event handler
self.addEventListener('push', (event: PushEvent) => {
  const raw = event.data ? (event.data.json() as unknown) : null;
  const data: PushPayload =
    raw && typeof raw === 'object'
      ? (raw as PushPayload)
      : { title: 'QuizGoal 2026' };

  const options: NotificationOptionsWithVibrate = {
    body: data.body || '',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    vibrate: [200, 100, 200],
    tag: data.tag || 'quizgoal',
    data: { url: data.url || '/' },
    requireInteraction: true,
    silent: false,
  };

  event.waitUntil(self.registration.showNotification(data.title || 'QuizGoal 2026', options));
});

// Notification click handler
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();
  const notifData = event.notification.data as NotificationData | undefined;
  const urlToOpen = notifData?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      return self.clients.openWindow(urlToOpen);
    })
  );
});

// Offline fallback for navigation requests
self.addEventListener('fetch', (event: FetchEvent) => {
  if (event.request.mode !== 'navigate') return;

  event.respondWith(
    fetch(event.request).catch(() => {
      return caches.match('/offline.html').then((offlineResponse) => {
        if (offlineResponse) return offlineResponse;
        return caches.match('/').then((rootResponse) => {
          if (rootResponse) return rootResponse;
          return new Response(
            '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>QuizGoal - Offline</title><style>body{background:#0a1628;color:#fff;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0;font-family:sans-serif;text-align:center;padding:20px}h1{font-size:3rem;margin-bottom:0.5rem}p{color:#999;max-width:400px;margin:0 auto;line-height:1.6}.ball{font-size:4rem;margin-bottom:1rem}</style></head><body><div><div class="ball">⚽</div><h1>Offline</h1><p>You are currently offline. Connect to the internet to use QuizGoal 2026.</p></div></body></html>',
            { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
          );
        });
      });
    })
  );
});

// Activate event - clean old caches
self.addEventListener('activate', (event: ExtendableEvent) => {
  const cacheWhitelist = [
    'supabase-api-cache',
    'supabase-storage-cache',
    'google-fonts-cache',
    'image-cache',
    'workbox-precache',
  ];

  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (!cacheWhitelist.includes(cacheName)) {
            return caches.delete(cacheName);
          }
          return Promise.resolve(false);
        })
      );
    })
  );
});

